#!/bin/bash

echo "TYPE=Ethernet
BOOTPROTO=static
DEVICE=eth1
ONBOOT=yes
BRIDGE=br-mgmt1" > /etc/sysconfig/network-scripts/ifcfg-eth1

echo "TYPE=Bridge
BOOTPROTO=static
DEVICE=br-mgmt1
METRIC=0
ONBOOT=yes
IPADDR=172.172.3.232
NETMASK=255.255.255.0
GATEWAY=172.172.3.1" > /etc/sysconfig/network-scripts/ifcfg-br-mgmt1

echo "TYPE=Ethernet
BOOTPROTO=static
DEVICE=eth2
ONBOOT=yes
BRIDGE=br-mgmt" > /etc/sysconfig/network-scripts/ifcfg-eth2

echo "TYPE=Bridge
BOOTPROTO=static
DEVICE=br-mgmt
METRIC=1
ONBOOT=yes
IPADDR=10.10.10.6
NETMASK=255.255.255.0
GATEWAY=10.10.10.1" > /etc/sysconfig/network-scripts/ifcfg-br-mgmt

echo "TYPE=Ethernet
BOOTPROTO=static
DEVICE=eth3
ONBOOT=yes
BRIDGE=br-vlan" > /etc/sysconfig/network-scripts/ifcfg-eth3

echo "TYPE=Bridge
BOOTPROTO=static
DEVICE=br-vlan
ONBOOT=yes" > /etc/sysconfig/network-scripts/ifcfg-br-vlan

echo "TYPE=Ethernet
BOOTPROTO=static
DEVICE=eth4
ONBOOT=yes
BRIDGE=br-vxlan" > /etc/sysconfig/network-scripts/ifcfg-eth4

echo "TYPE=Bridge
BOOTPROTO=static
DEVICE=br-vxlan
ONBOOT=yes" > /etc/sysconfig/network-scripts/ifcfg-br-vxlan

echo "TYPE=Ethernet
BOOTPROTO=static
DEVICE=eth5
ONBOOT=yes
BRIDGE=br-storage" > /etc/sysconfig/network-scripts/ifcfg-eth5

echo "TYPE=Bridge
BOOTPROTO=static
DEVICE=br-storage
METRIC=2
ONBOOT=yes
IPADDR=10.10.10.7
NETMASK=255.255.255.0
GATEWAY=10.10.10.1" > /etc/sysconfig/network-scripts/ifcfg-br-storage

